export const RISK_SIGNAL_CODE = {
  PAN_FORMAT_INVALID: "PAN_FORMAT_INVALID",
  PAN_GSTIN_MISMATCH: "PAN_GSTIN_MISMATCH",
  TDS_NO_PAN_PENALTY_RATE: "TDS_NO_PAN_PENALTY_RATE",
  TDS_SECTION_AMBIGUOUS: "TDS_SECTION_AMBIGUOUS",
  TDS_BELOW_THRESHOLD: "TDS_BELOW_THRESHOLD",
  TOTAL_AMOUNT_ABOVE_EXPECTED: "TOTAL_AMOUNT_ABOVE_EXPECTED",
  TOTAL_AMOUNT_BELOW_MINIMUM: "TOTAL_AMOUNT_BELOW_MINIMUM",
  DUE_DATE_TOO_FAR: "DUE_DATE_TOO_FAR",
  MISSING_MANDATORY_FIELDS: "MISSING_MANDATORY_FIELDS",
  DUPLICATE_INVOICE_NUMBER: "DUPLICATE_INVOICE_NUMBER",
  VENDOR_BANK_CHANGED: "VENDOR_BANK_CHANGED",
  IRN_MISSING: "IRN_MISSING",
  IRN_FORMAT_INVALID: "IRN_FORMAT_INVALID",
  MSME_PAYMENT_OVERDUE: "MSME_PAYMENT_OVERDUE",
  MSME_PAYMENT_DUE_SOON: "MSME_PAYMENT_DUE_SOON",
  SENDER_FREEMAIL: "SENDER_FREEMAIL",
  SENDER_DOMAIN_MISMATCH: "SENDER_DOMAIN_MISMATCH",
  SENDER_FIRST_TIME: "SENDER_FIRST_TIME",
  BANK_PAYMENT_VERIFIED: "BANK_PAYMENT_VERIFIED",
} as const;

export type RiskSignalCode = (typeof RISK_SIGNAL_CODE)[keyof typeof RISK_SIGNAL_CODE];
