#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
INPUT_FILE="$REPO_ROOT/docs/loc-tracker/loc-history.json"
OUTPUT_FILE="$REPO_ROOT/docs/loc-tracker/loc-graph.html"

if [[ ! -f "$INPUT_FILE" ]]; then
  echo "Error: $INPUT_FILE not found. Run loc-tracker.sh first."
  exit 1
fi

JSON_DATA=$(cat "$INPUT_FILE")

cat > "$OUTPUT_FILE" << 'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>LedgerBuddy - Lines of Code History</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    background: #0f1117;
    color: #e1e4e8;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, sans-serif;
    padding: 2rem;
    min-height: 100vh;
  }
  h1 {
    font-size: 1.75rem;
    font-weight: 600;
    margin-bottom: 0.25rem;
    color: #f0f3f6;
  }
  .subtitle {
    color: #8b949e;
    font-size: 0.875rem;
    margin-bottom: 2rem;
  }
  .chart-container {
    position: relative;
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 0.75rem;
    padding: 1.5rem;
    margin-bottom: 2rem;
  }
  .stats {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 1rem;
    margin-bottom: 2rem;
  }
  .stat-card {
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 0.75rem;
    padding: 1.25rem;
  }
  .stat-label {
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #8b949e;
    margin-bottom: 0.25rem;
  }
  .stat-value {
    font-size: 1.5rem;
    font-weight: 700;
  }
  .stat-value.backend { color: #58a6ff; }
  .stat-value.frontend { color: #3fb950; }
  .stat-value.tests { color: #d2a8ff; }
  .stat-value.total { color: #f0f3f6; }
  .stat-delta {
    font-size: 0.75rem;
    color: #8b949e;
    margin-top: 0.25rem;
  }
  .stat-delta.positive { color: #3fb950; }
  .stat-delta.negative { color: #f85149; }
  footer {
    text-align: center;
    color: #484f58;
    font-size: 0.75rem;
    margin-top: 2rem;
  }
</style>
</head>
<body>

<h1>LedgerBuddy LOC History</h1>
<p class="subtitle">Lines of code tracked across git history</p>

<div class="stats" id="stats"></div>

<div class="chart-container">
  <canvas id="locChart"></canvas>
</div>

<footer>Generated by loc-tracker.sh</footer>

<script>
const DATA = __LOC_DATA_PLACEHOLDER__;

const latest = DATA[DATA.length - 1];
const prev = DATA.length > 1 ? DATA[DATA.length - 2] : null;

function fmt(n) { return n.toLocaleString(); }
function delta(cur, old) {
  if (!old) return '';
  const d = cur - old;
  const pct = old > 0 ? ((d / old) * 100).toFixed(1) : '0.0';
  const sign = d >= 0 ? '+' : '';
  const cls = d >= 0 ? 'positive' : 'negative';
  return `<div class="stat-delta ${cls}">${sign}${fmt(d)} (${sign}${pct}%)</div>`;
}

document.getElementById('stats').innerHTML = `
  <div class="stat-card">
    <div class="stat-label">Backend</div>
    <div class="stat-value backend">${fmt(latest.backend)}</div>
    ${delta(latest.backend, prev?.backend)}
  </div>
  <div class="stat-card">
    <div class="stat-label">Frontend</div>
    <div class="stat-value frontend">${fmt(latest.frontend)}</div>
    ${delta(latest.frontend, prev?.frontend)}
  </div>
  <div class="stat-card">
    <div class="stat-label">Tests</div>
    <div class="stat-value tests">${fmt(latest.tests)}</div>
    ${delta(latest.tests, prev?.tests)}
  </div>
  <div class="stat-card">
    <div class="stat-label">Total</div>
    <div class="stat-value total">${fmt(latest.total)}</div>
    ${delta(latest.total, prev?.total)}
  </div>
`;

const labels = DATA.map(d => d.commit);
const dates = DATA.map(d => d.date);
const messages = DATA.map(d => d.message);

const ctx = document.getElementById('locChart').getContext('2d');
new Chart(ctx, {
  type: 'line',
  data: {
    labels,
    datasets: [
      {
        label: 'Total',
        data: DATA.map(d => d.total),
        borderColor: '#f0f3f6',
        backgroundColor: 'rgba(240,243,246,0.05)',
        borderWidth: 2,
        pointRadius: 2,
        pointHoverRadius: 5,
        fill: false,
        tension: 0.3,
      },
      {
        label: 'Backend',
        data: DATA.map(d => d.backend),
        borderColor: '#58a6ff',
        backgroundColor: 'rgba(88,166,255,0.05)',
        borderWidth: 2,
        pointRadius: 2,
        pointHoverRadius: 5,
        fill: false,
        tension: 0.3,
      },
      {
        label: 'Frontend',
        data: DATA.map(d => d.frontend),
        borderColor: '#3fb950',
        backgroundColor: 'rgba(63,185,80,0.05)',
        borderWidth: 2,
        pointRadius: 2,
        pointHoverRadius: 5,
        fill: false,
        tension: 0.3,
      },
      {
        label: 'Tests',
        data: DATA.map(d => d.tests),
        borderColor: '#d2a8ff',
        backgroundColor: 'rgba(210,168,255,0.05)',
        borderWidth: 2,
        pointRadius: 2,
        pointHoverRadius: 5,
        fill: false,
        tension: 0.3,
      },
    ],
  },
  options: {
    responsive: true,
    maintainAspectRatio: true,
    aspectRatio: 2.5,
    interaction: {
      mode: 'index',
      intersect: false,
    },
    plugins: {
      tooltip: {
        backgroundColor: '#1c2128',
        titleColor: '#f0f3f6',
        bodyColor: '#e1e4e8',
        borderColor: '#30363d',
        borderWidth: 1,
        padding: 12,
        callbacks: {
          title: function(items) {
            const idx = items[0].dataIndex;
            return `${labels[idx]} (${dates[idx]})`;
          },
          afterTitle: function(items) {
            const idx = items[0].dataIndex;
            const msg = messages[idx];
            return msg.length > 80 ? msg.substring(0, 77) + '...' : msg;
          },
          label: function(item) {
            return `${item.dataset.label}: ${item.parsed.y.toLocaleString()} lines`;
          },
        },
      },
      legend: {
        position: 'top',
        labels: {
          color: '#8b949e',
          usePointStyle: true,
          pointStyle: 'circle',
          padding: 20,
          font: { size: 13 },
        },
      },
    },
    scales: {
      x: {
        ticks: {
          color: '#484f58',
          maxRotation: 45,
          autoSkip: true,
          maxTicksLimit: 30,
          font: { size: 10 },
        },
        grid: { color: 'rgba(48,54,61,0.5)' },
      },
      y: {
        ticks: {
          color: '#484f58',
          callback: function(v) { return v.toLocaleString(); },
          font: { size: 11 },
        },
        grid: { color: 'rgba(48,54,61,0.5)' },
        beginAtZero: true,
      },
    },
  },
});
</script>
</body>
</html>
HTMLEOF

python3 -c "
import json, sys

with open('$INPUT_FILE') as f:
    data = json.load(f)

json_str = json.dumps(data)

with open('$OUTPUT_FILE') as f:
    html = f.read()

html = html.replace('__LOC_DATA_PLACEHOLDER__', json_str)

with open('$OUTPUT_FILE', 'w') as f:
    f.write(html)
"

echo "Generated $OUTPUT_FILE with $(python3 -c "import json; print(len(json.load(open('$INPUT_FILE'))))" ) data points."
