export const PLATFORM_URL_PATHS = {
  healthRoot: "/health",
  healthReady: "/health/ready",
  authToken: "/auth/token",
  authLogin: "/auth/login",
  authCallback: "/auth/callback",
  authRefresh: "/auth/refresh",
  authChangePassword: "/auth/change-password",
  session: "/session",
  bankAaCallback: "/bank/aa-callback",
  bankMockCallback: "/bank/mock-callback",
  bankConsentNotify: "/bank/consent-notify",
  bankFiNotify: "/bank/fi-notify",
  connectGmail: "/connect/gmail",
  connectGmailCallback: "/connect/gmail/callback",
  platformTenantsOnboardAdmin: "/platform/tenants/onboard-admin",
  platformTenantEnabled: "/platform/tenants/:tenantId/enabled",
  platformTenantsUsage: "/platform/tenants/usage",
  adminWorkflowHealth: "/admin/workflow-health",
  complianceTdsRates: "/compliance/tds-rates",
  complianceTdsRateBySection: "/compliance/tds-rates/:section",
  complianceTdsSections: "/compliance/tds-sections",
  complianceRiskSignals: "/compliance/risk-signals"
} as const;
