export const INVOICE_CTX = {
  OCR_RESULT: "invoice.ocrResult",
  OCR_BLOCKS: "invoice.ocrBlocks",
  OCR_PAGE_IMAGES: "invoice.ocrPageImages",
  OCR_TOKENS: "invoice.ocrTokens",
  OCR_CONFIDENCE: "invoice.ocrConfidence",
  EXTRACT_FIELDS: "invoice.extractFields",
  ENHANCED_OCR: "invoice.enhancedOcr",
  RANKED_CANDIDATES: "invoice.rankedCandidates",
  PRIMARY_CANDIDATE: "invoice.primaryCandidate",
  PRIMARY_TEXT: "invoice.primaryText",
  AUGMENTED_TEXT: "invoice.augmentedText",
  PRE_OCR_LANGUAGE: "invoice.preOcrLanguage",
  LANGUAGE_RESOLUTION: "invoice.languageResolution",
  BASELINE_PARSED: "invoice.baselineParsed",
  FIELD_CANDIDATES: "invoice.fieldCandidates",
  FIELD_REGIONS: "invoice.fieldRegions",
  VENDOR_TEMPLATE: "invoice.vendorTemplate",
  ENGINE_RESULT: "invoice.engineResult",
} as const;
